//! DoP (DSD over PCM, spec 1.1) encoding — Phase 1 of DSD support.
//!
//! DoP carries the untouched 1-bit DSD stream inside 24-bit PCM samples so it
//! survives any bit-transparent PCM path: each 24-bit word holds a marker
//! byte in bits 23–16 (alternating `0x05`/`0xFA` on successive words of the
//! same channel, synchronised across channels) and 16 DSD bits below it —
//! the older byte in bits 15–8, the newer in bits 7–0, MSB = oldest sample.
//! A DoP-aware DAC spots the marker sequence and unpacks the original bits;
//! anything else just plays very quiet high-frequency noise.
//!
//! The PCM carrier runs at `dsd_rate / 16` (DSD64 → 176.4 kHz, DSD128 →
//! 352.8 kHz, DSD256 → 705.6 kHz), so bit-perfect DoP only needs a device
//! that accepts ≥24-bit PCM at that rate.
//!
//! Input is the [`DsdReader`](super::DsdReader) byte stream: MSB-first,
//! channel-interleaved — exactly what both containers are normalised to.

use std::fs::File;
use std::io::{BufReader, Read, Seek};
use std::path::Path;

use super::DsdReader;

/// The two alternating DoP marker bytes. The spec allows starting with
/// either; we start with `0x05`.
pub const DOP_MARKERS: [u8; 2] = [0x05, 0xFA];

/// DSD "silence": a repeating `01101001…` pattern that idles a sigma-delta
/// DAC near zero (all-zero bits would be full-scale negative DC). Used to pad
/// a stream that ends on an odd DSD byte.
pub const DSD_SILENCE: u8 = 0x69;

/// PCM carrier rate for a DSD rate: 16 DSD bits ride in each 24-bit sample.
pub fn carrier_rate(dsd_rate: u32) -> u32 {
    dsd_rate / 16
}

/// Build one DoP word from a marker and two DSD bytes (older first).
/// The 24-bit word sits in the low bits of the returned `u32`.
///
/// Test-only since 1.4.3: production never assembles a marked word here, it is
/// assembled at the output boundary by `bitperfect::format::DopState`.
#[cfg(test)]
#[inline]
pub fn dop_word(marker: u8, older: u8, newer: u8) -> u32 {
    (marker as u32) << 16 | (older as u32) << 8 | newer as u32
}

/// The marker-free half of a DoP word: two DSD bytes, older in bits 15–8.
///
/// This is what travels through the output ring. The marker is applied at the
/// render boundary by `bitperfect::format::DopState`, because it belongs to
/// the carrier frame the device is about to receive rather than to the audio —
/// and because silence generated by the render thread (prefill, pause,
/// underrun, drain) needs a valid marker too, which a decode-side packer
/// cannot supply.
#[inline]
pub fn payload_word(older: u8, newer: u8) -> u32 {
    (older as u32) << 8 | newer as u32
}

/// A [`DsdReader`] that yields interleaved 16-bit DoP *payloads* — the DSD bit
/// stream cut into carrier-frame-sized pieces, with no marker. This is the
/// unit the bit-perfect output path consumes.
pub struct DopStream<R: Read + Seek> {
    reader: DsdReader<R>,
    channels: usize,
    /// Scratch for the raw DSD bytes of one read.
    buf: Vec<u8>,
    /// The file this came from, where there is one. Empty for a stream built
    /// over an in-memory reader, which only tests do.
    path: std::path::PathBuf,
}

impl<R: Read + Seek> DopStream<R> {
    pub fn new(reader: DsdReader<R>) -> Self {
        let channels = (reader.info().channels as usize).max(1);
        DopStream { reader, channels, buf: Vec::new(), path: std::path::PathBuf::new() }
    }

    /// Record where this stream came from, so a gapless boundary can name the
    /// track that begins there.
    pub fn with_path(mut self, path: &Path) -> Self {
        self.path = path.to_path_buf();
        self
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn info(&self) -> &super::DsdInfo {
        self.reader.info()
    }

    /// PCM carrier rate of this stream.
    pub fn carrier_rate(&self) -> u32 {
        carrier_rate(self.reader.info().sample_rate)
    }

    /// Total PCM frames the stream will yield (including a padded tail).
    #[allow(dead_code)] // for a future progress/duration readout on the DoP path
    pub fn total_pcm_frames(&self) -> u64 {
        self.reader.total_frames().div_ceil(2)
    }

    /// Read up to `max_frames` carrier frames of bare 16-bit DSD payload into
    /// `out` (appended, interleaved). Returns frames appended; 0 = end of
    /// stream.
    ///
    /// A trailing odd DSD frame is completed with [`DSD_SILENCE`] so the last
    /// 16-bit slot is full — that padding is part of the payload and is the
    /// one place a file's own bits are extended rather than carried.
    pub fn read_payload(&mut self, max_frames: usize, out: &mut Vec<u32>) -> std::io::Result<usize> {
        let ch = self.channels;
        self.buf.clear();
        self.buf.resize(max_frames * 2 * ch, 0);
        // Fill as much as the reader will give — it may return short reads
        // near block boundaries, but only whole DSD frames.
        let mut got = 0usize;
        while got < max_frames * 2 {
            let n = self.reader.read_frames(&mut self.buf[got * ch..])?;
            if n == 0 {
                break;
            }
            got += n;
        }
        if got == 0 { return Ok(0); }

        let whole = got / 2;
        let odd = got % 2 == 1;
        out.reserve((whole + odd as usize) * ch);
        for fr in 0..whole {
            let base = fr * 2 * ch;
            for c in 0..ch {
                out.push(payload_word(self.buf[base + c], self.buf[base + ch + c]));
            }
        }
        if odd {
            let base = whole * 2 * ch;
            for c in 0..ch {
                out.push(payload_word(self.buf[base + c], DSD_SILENCE));
            }
        }
        Ok(whole + odd as usize)
    }

    /// Seek to a PCM-frame position (each PCM frame = 16 DSD samples). The
    /// marker phase is not this type's business and is unaffected: the render
    /// thread keeps counting frames straight through a seek, so the
    /// alternation never breaks.
    pub fn seek_to_pcm_frame(&mut self, frame: u64) -> std::io::Result<()> {
        self.reader.seek_to_frame(frame * 2)
    }
}

pub type DopFileStream = DopStream<BufReader<File>>;

/// Open a DSD file and wrap it as a ready-to-read DoP word stream.
pub fn open_dop_stream(path: &Path) -> Result<DopFileStream, String> {
    Ok(DopStream::new(super::open_reader(path)?).with_path(path))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::super::{parse_dsf, tests::make_dsf, DSD64_RATE};
    use super::*;
    use std::io::Cursor;

    #[test]
    fn carrier_rates() {
        assert_eq!(carrier_rate(2_822_400), 176_400); // DSD64
        assert_eq!(carrier_rate(5_644_800), 352_800); // DSD128
        assert_eq!(carrier_rate(11_289_600), 705_600); // DSD256
        assert_eq!(carrier_rate(22_579_200), 1_411_200); // DSD512
    }

    #[test]
    fn word_layout() {
        // Marker in bits 23-16, older DSD byte in 15-8, newer in 7-0.
        assert_eq!(dop_word(0x05, 0xAB, 0xCD), 0x05ABCD);
        assert_eq!(dop_word(0xFA, 0x00, 0xFF), 0xFA00FF);
    }

    #[test]
    fn dop_stream_end_to_end_over_dsf() {
        // 2ch DSF, block size 4, 2 block-rows = 8 DSD frames = 4 PCM frames.
        // DSF is LSB-first, so the packed bytes are the bit-reversed input.
        let blocks = vec![
            vec![vec![0x01, 0x02, 0x03, 0x04], vec![0x11, 0x12, 0x13, 0x14]],
            vec![vec![0x05, 0x06, 0x07, 0x08], vec![0x15, 0x16, 0x17, 0x18]],
        ];
        let file = make_dsf(2, DSD64_RATE, 1, 64, 4, &blocks, None);
        let info = parse_dsf(&mut Cursor::new(&file)).unwrap();
        let reader = DsdReader::new(Cursor::new(&file), info).unwrap();
        let mut s = DopStream::new(reader);
        assert_eq!(s.carrier_rate(), 176_400);
        assert_eq!(s.total_pcm_frames(), 4);

        let mut words = Vec::new();
        // Ask for more than exists — should deliver exactly 4 then 0.
        assert_eq!(s.read_payload(16, &mut words).unwrap(), 4);
        assert_eq!(s.read_payload(16, &mut words).unwrap(), 0);

        // Payloads only: no marker anywhere in the ring, and every word fits
        // in 16 bits.
        let r = |b: u8| b.reverse_bits();
        assert_eq!(words, vec![
            payload_word(r(0x01), r(0x02)), payload_word(r(0x11), r(0x12)),
            payload_word(r(0x03), r(0x04)), payload_word(r(0x13), r(0x14)),
            payload_word(r(0x05), r(0x06)), payload_word(r(0x15), r(0x16)),
            payload_word(r(0x07), r(0x08)), payload_word(r(0x17), r(0x18)),
        ]);
        assert!(words.iter().all(|&w| w <= 0xFFFF), "a marker leaked into the ring");
    }

    /// An odd DSD frame count leaves half a carrier frame; the missing half is
    /// DSD silence, not a zero byte and not a dropped sample.
    #[test]
    fn an_odd_tail_is_padded_with_dsd_silence() {
        // 3 DSD frames of 2ch: 1 whole carrier frame + 1 padded one.
        let blocks = vec![vec![vec![0x01, 0x02, 0x03], vec![0x11, 0x12, 0x13]]];
        let file = make_dsf(2, DSD64_RATE, 1, 24, 3, &blocks, None);
        let info = parse_dsf(&mut Cursor::new(&file)).unwrap();
        let mut s = DopStream::new(DsdReader::new(Cursor::new(&file), info).unwrap());
        let mut out = Vec::new();
        assert_eq!(s.read_payload(16, &mut out).unwrap(), 2);
        let r = |b: u8| b.reverse_bits();
        assert_eq!(out, vec![
            payload_word(r(0x01), r(0x02)), payload_word(r(0x11), r(0x12)),
            payload_word(r(0x03), DSD_SILENCE), payload_word(r(0x13), DSD_SILENCE),
        ]);
    }

    #[test]
    fn dop_stream_seek() {
        let blocks = vec![
            vec![vec![0x01, 0x02, 0x03, 0x04], vec![0x11, 0x12, 0x13, 0x14]],
        ];
        let file = make_dsf(2, DSD64_RATE, 1, 32, 4, &blocks, None);
        let info = parse_dsf(&mut Cursor::new(&file)).unwrap();
        let reader = DsdReader::new(Cursor::new(&file), info).unwrap();
        let mut s = DopStream::new(reader);
        s.seek_to_pcm_frame(1).unwrap();
        let mut words = Vec::new();
        assert_eq!(s.read_payload(4, &mut words).unwrap(), 1);
        let r = |b: u8| b.reverse_bits();
        assert_eq!(words, vec![
            payload_word(r(0x03), r(0x04)),
            payload_word(r(0x13), r(0x14)),
        ]);
    }
}
